USE master;
IF DB_ID('CourseManagerDB') IS NOT NULL
   DROP DATABASE CourseManagerDB;
GO
CREATE DATABASE CourseManagerDB;
GO

USE CourseManagerDB;
GO
CREATE TABLE [Courses] (
	CoursID			INT				NOT NULL IDENTITY(1, 1),
	Name			NVARCHAR(100)	NOT NULL,
	[Description]	NVARCHAR(4000)	NULL,
	Price			MONEY			NOT NULL,
  CONSTRAINT [PK_COURSES_CoursID] PRIMARY KEY CLUSTERED
  (
  [CoursID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Schedule] (
	ScheduleID	INT			NOT NULL IDENTITY(1, 1),
	CoursID		INT			NOT NULL,
	StartDate	DATETIME2	NOT NULL,
	EndDate		DATETIME2	NOT NULL,
  CONSTRAINT [PK_SCHEDULE_ScheduleID] PRIMARY KEY CLUSTERED
  (
  [ScheduleID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF),
  CONSTRAINT FK_Schedule_CoursID_Courses FOREIGN KEY (CoursID)
	REFERENCES Courses(CoursID)

)
GO



